"""entidades agregadas: empresa, ingreso_gasto

Revision ID: 25c5bb1e92c5
Revises: 5d31e501aed6
Create Date: 2023-03-22 22:00:28.545224

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25c5bb1e92c5'
down_revision = '5d31e501aed6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('empresa',
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('nombre_empresa', sa.String(length=255), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.usuario_id'], ),
    sa.PrimaryKeyConstraint('empresa_id')
    )
    op.create_table('ingreso_gasto',
    sa.Column('ingreso_gasto_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ingreso', sa.Integer(), nullable=True),
    sa.Column('gasto', sa.Integer(), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.empresa_id'], ),
    sa.PrimaryKeyConstraint('ingreso_gasto_id')
    )
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nombre_completo', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_column('nombre_completo')

    op.drop_table('ingreso_gasto')
    op.drop_table('empresa')
    # ### end Alembic commands ###
