"""empty message

Revision ID: 51837e466e9f
Revises: 
Create Date: 2023-03-15 00:15:55.366460

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51837e466e9f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuario',
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('contrasena', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('usuario_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuario')
    # ### end Alembic commands ###
