"""usuario y contrasena

Revision ID: 5d31e501aed6
Revises: 51837e466e9f
Create Date: 2023-03-15 00:18:27.787503

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5d31e501aed6'
down_revision = '51837e466e9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('usuario', sa.String(length=255), nullable=False))
        batch_op.drop_column('username')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', mysql.VARCHAR(length=255), nullable=False))
        batch_op.drop_column('usuario')

    # ### end Alembic commands ###
